### ISSUE TITLE
MG review - Anicipated Changes

### ISSUE THREAD

**Issue by vajihehm** [hananezlitni/HZ-CAS741-Project#19]
@hananezlitni  I did not make sense of AC4 “The assumptions related to the input  data.” as Anticipated Change. If you mean format of the input parameters  external to the Driver Program please clarify it. ( Regarding to the CA  I did not undrestand if user inputs data or not. Dr smith has commented  the user does not input data.)

**Comment by hananezlitni** [comment]
@vajihehm The user inputs data (e.g. objective function, linear constraints,...) in a driver program, and since the driver program calls the LoSMS library, the data will be passed to the library to perform the calculations. 
In the CA, I have an assumption about the type of inequality allowed in the linear constraints. Therefore, I added this as an anticipated change since all types of inequalities can be allowed in a future expansion of the project. To be clearer, I added to the anticipated change a reference to the CA so the reader can check that. Thank you for your comment (:
