### ISSUE TITLE
Simplex Solver MIS Peere Review: #1

### ISSUE THREAD

**Issue by oluowoj** [hananezlitni/HZ-CAS741-Project#24]
@hananezlitni in this section I assume that validateInputs, is validating a set of inputs and throws an exception if the input is not valid. Should this not have the "In and Out" populated with the corresponding parameters for tis function? 

Also is validateInputs going to be used by external modules or just within the input module? Just wondering.

**Comment by hananezlitni** [comment]
@oluowoj You are correct. I meant to add the inputs as state variables, but forgot to do so. I fixed it. It doesn't have an "Out" because it would throw an exception in the case of a violation, so I thought that there's no need for a return value.

validateInputs is not going to be used by external modules, because the inputs will already be validated when they're passed to the other modules. I'm starting to think that it should be a local function not an access program. What do you think about that?
