### ISSUE TITLE
Formatting of Data Definitions Section

### ISSUE THREAD

**Issue by PeaWagon** [hananezlitni/HZ-CAS741-Project#5]
For DD1, Z' is not in your table of symbols, nor does it appear in IM2. 

For DD2, what are the elements of your matrix representing (i.e. a11 and b1). I usually put a solid vertical bar to indicate where the matrix has been augmented. What is the relationship between n and m? Define these subscripts. Furthermore, it looks as if n and m both represent the number of rows. If you wish to designate a number of columns, perhaps include a final "a" column before the "b" column, and write bm as bn instead. Without augmentation, does the matrix have to be square or not? Perhaps you need assumptions as to the type of matrix you have here.

For DD3, I would write positive real number rather than non-negative variable (I am assuming that your value for Sn is not imaginary).

**Comment by hananezlitni** [comment]
**1. For DD1, Z' is not in your table of symbols, nor does it appear in IM2.**

Added Z' to IM2 and the table of symbols.

**2. For DD2, what are the elements of your matrix representing (i.e. a11 and b1). I usually put a solid vertical bar to indicate where the matrix has been augmented. What is the relationship between n and m? Define these subscripts. Furthermore, it looks as if n and m both represent the number of rows. If you wish to designate a number of columns, perhaps include a final "a" column before the "b" column, and write bm as bn instead. Without augmentation, does the matrix have to be square or not? Perhaps you need assumptions as to the type of matrix you have here.**

For DD2, I defined "a", "b" (real numbers) and "n" (a natural number) and I changed "bm" to "bn". The matrix does not have to be square. The thing is, the user will enter the inputs as regular functions (e.g. Z= 2x1 + 3x2 ...). In order to solve the function, the tool will setup the matrix and perform the simplex method steps. Therefore, I'm not sure if it's right to make an assumption about the matrix since it's something that the tool will do not the user. 

@smiths Dr. Smith, what do you think?

**3. For DD3, I would write positive real number rather than non-negative variable (I am assuming that your value for Sn is not imaginary).**

Thank you for your advice. I rephrased the sentence. Sn can also be zero so I made that clear.

**Comment by hananezlitni** [comment]
6e31a5c applies the first and the third comments (in sections 2.2 and 5.3).

The last part of the second comment is not addressed yet.

**Comment by smiths** [comment]
@hananezlitni, you are correct that an "external" tool of some kind will provide your library with the data that it needs.  You shouldn't be worrying about direct interaction with the user.  Some other program takes care of that.  Your CA should say any constraints on what makes a valid matrix.  For instance, an empty matrix would not be valid.  You should have routines available to test to ensure the data satisfies any rules that you might have.  At some points the responsibility switches to the user of the external tool.  The user needs to give it good data.  For the things you can't test for, you have to make it the responsibility of the program/person using your library.

**Comment by hananezlitni** [comment]
@smiths thank you for the explanation.

**Comment by hananezlitni** [comment]
I am closing the issue since everything is addressed.
